# Generated by Django 3.2.25 on 2024-09-14 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('marital_status', models.CharField(max_length=10, choices=[
                    ('single', 'Single'),
                    ('married', 'Married'),
                    ('divorced', 'Divorced'),
                    ('widowed', 'Widowed')
                ], default='single')),
                ('hired_date', models.DateField()),  # Updated to DateField
                ('field_of_study', models.CharField(max_length=200)),
                ('educational_level', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('employee_status', models.CharField(max_length=10, choices=[
                    ('active', 'Active'),
                    ('inactive', 'Inactive'),
                    ('terminated', 'Terminated'),
                    ('retired', 'Retired')
                ], default='active')),
                ('contact_number', models.CharField(max_length=15)),
                ('registered_at', models.DateTimeField(auto_now=True, verbose_name='Registered at')),
                ('registered_by', django_currentuser.db.models.fields.CurrentUserField(
                    default=django_currentuser.middleware.get_current_authenticated_user, null=True,
                    on_delete=django.db.models.deletion.CASCADE, related_name='staff_registered_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(
                    default=django_currentuser.middleware.get_current_authenticated_user, null=True,
                    on_delete=django.db.models.deletion.CASCADE, related_name='staff_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=50, unique=True)),
                ('valid_until', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employees.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceInline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Institution', models.CharField(max_length=150)),
                ('Position', models.CharField(max_length=150)),
                ('Educational_level', models.CharField(max_length=150)),
                ('Field_of_study', models.CharField(max_length=150)),
                ('From_date', models.CharField(max_length=150)),
                ('To_date', models.CharField(max_length=150)),
                ('Net_duration', models.CharField(max_length=150)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.staffprofile')),
            ],
            options={
                'verbose_name': 'Experience inline',
                'verbose_name_plural': 'Experience inlines',
            },
        ),
    ]
