# Generated by Django 5.1.4 on 2025-03-07 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registered at'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=150)),
                ('educational_level', models.CharField(max_length=150)),
                ('field_of_study', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('net_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='employees.staffprofile')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-to_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('leave_type', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Vacation Leave', 'Vacation Leave')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MotorHome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('schedule_date', models.DateField(help_text='Scheduled date for the employee in the motor home queue.')),
                ('motor_on_time', models.DateTimeField(blank=True, help_text='Timestamp when the motor was turned on.', null=True)),
                ('motor_off_time', models.DateTimeField(blank=True, help_text='Timestamp when the motor was turned off.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorhome_entries', to='employees.staffprofile')),
            ],
            options={
                'ordering': ['schedule_date', 'motor_on_time'],
            },
        ),
        migrations.DeleteModel(
            name='ExperienceInline',
        ),
    ]
