# Generated by Django 5.1.7 on 2025-03-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_staffprofile_options_staffprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
