# Generated by Django 5.1.7 on 2025-03-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
