# Generated by Django 5.1.7 on 2025-03-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_delete_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
