# Generated by Django 5.1.7 on 2025-03-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='educational_level',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='field_of_study',
        ),
    ]
