# Generated by Django 5.1.7 on 2025-03-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_experience_educational_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='completed_date',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
