# Generated by Django 5.1.7 on 2025-03-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_staffprofile_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='completed_date',
            field=models.DateField(),
        ),
    ]
