# Generated by Django 5.1.7 on 2025-03-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_staffprofile_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=150),
            preserve_default=False,
        ),
    ]
