# Generated by Django 5.1.7 on 2025-03-31 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_staffprofile_gender'),
        ('setups', '0048_alter_block_status_alter_gaugewidth_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setups.department'),
            preserve_default=False,
        ),
    ]
