# Generated by Django 5.1.7 on 2025-03-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeeperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeperformance',
            name='rank',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
