# Generated by Django 5.1.7 on 2025-03-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employeeperformance_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeperformance',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
