# Generated by Django 5.0.4 on 2024-04-16 04:10

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateTimeField()),
                ('Deposite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Withdrawal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Registered_at', models.DateTimeField(auto_now=True, verbose_name='Registered at')),
                ('Registered_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl_by44', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_by44', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
