# Generated by Django 5.0.4 on 2024-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bankbook_balance_alter_bankbook_deposite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='Balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='Deposite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='Withdrawal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
