# Generated by Django 5.0.4 on 2024-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_bankbook_balance_alter_bankbook_deposite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
