# Generated by Django 5.0.4 on 2024-04-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bankbook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
