# Generated by Django 5.0.4 on 2024-04-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_bankbook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='Date',
            field=models.DateField(),
        ),
    ]
