# Generated by Django 5.0.4 on 2024-04-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_bankbook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='Balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='Deposite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='Withdrawal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
