# Generated by Django 5.0.6 on 2024-06-09 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaugeWidth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('width', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'widths',
            },
        ),
        migrations.CreateModel(
            name='Kebele',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kebele', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Kebeles',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('month_amharic', models.CharField(max_length=100, unique=True)),
                ('month_english', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Months',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('service', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('year', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Years',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('zone', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='Penality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('months', models.PositiveIntegerField()),
                ('penality', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=150)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.servicetype')),
            ],
            options={
                'verbose_name_plural': 'Penalities',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('value', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=150)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('consumption_from', models.PositiveIntegerField()),
                ('consumption_to', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=150)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.block')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.servicetype')),
            ],
        ),
    ]
