# Generated by Django 5.0.6 on 2024-06-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='block',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='consumption_from',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='consumption_to',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='name',
        ),
        migrations.AddField(
            model_name='tariff',
            name='block1',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='block2',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='block3',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='block4',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='block5',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='max_consumption',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='min_consumption',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
