# Generated by Django 5.0.6 on 2024-06-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_remove_tariff_block_remove_tariff_consumption_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='block1',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='block2',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='block3',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='block4',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='block5',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='max_consumption',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='min_consumption',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
