# Generated by Django 5.0.6 on 2024-06-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0003_alter_tariff_block1_alter_tariff_block2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=150),
        ),
    ]
