# Generated by Django 3.2.25 on 2024-07-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0005_reader'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Penality',
            new_name='Penalty',
        ),
        migrations.RenameField(
            model_name='penalty',
            old_name='penality',
            new_name='penalty',
        ),
    ]
