# Generated by Django 3.2.25 on 2024-08-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0006_auto_20240727_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='reader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setups.reader'),
            preserve_default=False,
        ),
    ]
