# Generated by Django 3.2.25 on 2024-09-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0008_auto_20240826_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Item lists',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Measurements',
            },
        ),
    ]
