# Generated by Django 3.2.25 on 2024-09-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0009_itemlists_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='months',
        ),
    ]
