# Generated by Django 3.2.25 on 2024-09-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0011_auto_20240918_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.service')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.servicetype')),
            ],
            options={
                'verbose_name_plural': 'Service charges',
            },
        ),
    ]
