# Generated by Django 3.2.25 on 2024-09-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0013_alter_zone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
