# Generated by Django 3.2.25 on 2024-09-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0014_alter_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='username',
            field=models.CharField(default=1, editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
