# Generated by Django 3.2.25 on 2024-09-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0015_reader_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='username',
        ),
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
