# Generated by Django 3.2.25 on 2024-09-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0017_auto_20240928_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.banktype')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.paymenttype')),
            ],
        ),
    ]
