# Generated by Django 3.2.25 on 2024-09-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0018_bankpaymenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.department')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.organization'),
        ),
    ]
