# Generated by Django 4.2 on 2024-11-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0020_grade_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionFormula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.grade')),
            ],
            options={
                'verbose_name_plural': 'Tuition formula',
            },
        ),
    ]
