# Generated by Django 4.2 on 2024-11-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0021_tuitionformula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionformula',
            old_name='Grade',
            new_name='grade',
        ),
    ]
