# Generated by Django 4.2 on 2024-11-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0022_rename_grade_tuitionformula_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionformula',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tuitionformula',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
