# Generated by Django 4.2 on 2024-11-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0024_transportformula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportformula',
            old_name='Fermata',
            new_name='fermata',
        ),
    ]
