# Generated by Django 4.2 on 2024-11-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0025_rename_fermata_transportformula_fermata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fermata',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Fermata',
            },
        ),
    ]
