# Generated by Django 4.2 on 2024-11-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0026_fermata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportformula',
            name='fermata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.fermata'),
        ),
    ]
