# Generated by Django 4.2 on 2024-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0028_other_registration_nutrition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltySchool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Penalties',
            },
        ),
    ]
