# Generated by Django 4.2 on 2024-11-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0029_penaltyschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
