# Generated by Django 4.2 on 2024-11-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0030_alter_nutrition_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penaltyschool',
            options={'verbose_name_plural': 'School penalties'},
        ),
    ]
