# Generated by Django 5.1.3 on 2024-11-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0032_academicformula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicformula',
            options={'verbose_name_plural': 'Academic formula'},
        ),
    ]
