# Generated by Django 5.1.3 on 2024-12-11 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0034_sponsorshiptype_transportcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicformula',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setups.grade'),
        ),
        migrations.AlterField(
            model_name='transportformula',
            name='fermata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setups.fermata'),
        ),
    ]
