# Generated by Django 5.1.3 on 2024-12-11 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0035_alter_academicformula_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setups.grade'),
        ),
        migrations.AlterField(
            model_name='tuitionformula',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setups.grade'),
        ),
    ]
