# Generated by Django 5.1.7 on 2025-03-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0036_alter_nutrition_grade_alter_tuitionformula_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportFormula',
        ),
    ]
