# Generated by Django 5.1.7 on 2025-03-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0038_delete_tuitionformula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fermata',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.DeleteModel(
            name='PenaltySchool',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SponsorshipType',
        ),
        migrations.DeleteModel(
            name='TransportCategory',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
