# Generated by Django 5.1.7 on 2025-03-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0039_delete_fermata_remove_nutrition_grade_delete_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicformula',
            name='academic_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academicformula',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
