# Generated by Django 5.1.7 on 2025-03-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0040_alter_academicformula_academic_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
