# Generated by Django 5.1.7 on 2025-03-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0041_delete_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicFormula',
        ),
    ]
