# Generated by Django 5.1.7 on 2025-03-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0042_delete_academicformula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankpaymenttype',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bankpaymenttype',
            name='payment_type',
        ),
        migrations.DeleteModel(
            name='BankType',
        ),
        migrations.DeleteModel(
            name='BankPaymentType',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
