# Generated by Django 5.1.7 on 2025-03-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0043_remove_bankpaymenttype_bank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kebele',
            options={},
        ),
    ]
