# Generated by Django 5.1.7 on 2025-03-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0044_alter_kebele_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gaugewidth',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicecharge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={},
        ),
    ]
