# Generated by Django 5.1.7 on 2025-03-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0046_task_content_type_task_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='object_id',
        ),
    ]
