# Generated by Django 5.1.7 on 2025-03-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0047_remove_task_content_type_remove_task_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=150),
        ),
        migrations.AlterField(
            model_name='gaugewidth',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='kebele',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='month',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='year',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50),
        ),
    ]
