# Generated by Django 5.0.6 on 2024-06-09 19:45

import django.db.models.deletion
import periods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=150, verbose_name='Month')),
                ('yid', models.CharField(max_length=150, verbose_name='Year id')),
                ('year', models.CharField(max_length=150, verbose_name='Year')),
            ],
            options={
                'db_table': 'Season',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InputDataCurrentSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.ForeignKey(default=periods.models.InputDataCurrentSeason.get_current_month_id, on_delete=django.db.models.deletion.CASCADE, related_name='smonthid', to='setups.month')),
                ('month', models.ForeignKey(default=periods.models.InputDataCurrentSeason.get_current_month, on_delete=django.db.models.deletion.CASCADE, related_name='smonth', to='setups.month')),
                ('year', models.ForeignKey(default=periods.models.InputDataCurrentSeason.get_current_year, on_delete=django.db.models.deletion.CASCADE, related_name='syear', to='setups.year')),
                ('yid', models.ForeignKey(default=periods.models.InputDataCurrentSeason.get_current_year_id, on_delete=django.db.models.deletion.CASCADE, related_name='syearid', to='setups.year')),
            ],
        ),
    ]
