# Generated by Django 5.1.3 on 2024-12-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0002_alter_season_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputdatacurrentseason',
            options={'verbose_name': 'Season change', 'verbose_name_plural': 'Season changes'},
        ),
    ]
