# Generated by Django 3.2.25 on 2024-09-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0019_auto_20240930_2156'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potablewaterservicetype',
            name='Service_title_amharic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.task'),
        ),
    ]
