# Generated by Django 3.2.25 on 2024-09-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0019_auto_20240930_2156'),
        ('process', '0002_alter_potablewaterservicetype_service_title_amharic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='Expense_title_amharic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.task'),
        ),
        migrations.AlterField(
            model_name='revenuetype',
            name='Revenue_title_amharic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.task'),
        ),
    ]
