# Generated by Django 4.2 on 2024-10-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20240930_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allexpense',
            options={'verbose_name': 'Expense performed management', 'verbose_name_plural': 'Expense performed management'},
        ),
        migrations.AlterModelOptions(
            name='allpotablewaterservicemanagement',
            options={'verbose_name': 'Potable water service performed management', 'verbose_name_plural': 'potable water service performed management'},
        ),
        migrations.AlterModelOptions(
            name='allrevenue',
            options={'verbose_name': 'Revenue  management', 'verbose_name_plural': 'Revenue performed management'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'verbose_name': 'Expense plan management', 'verbose_name_plural': 'Expense plan management'},
        ),
        migrations.AlterModelOptions(
            name='potablewaterservicetype',
            options={'verbose_name': 'Potable water service plan management', 'verbose_name_plural': 'Potable water service plan management'},
        ),
        migrations.AlterModelOptions(
            name='revenuetype',
            options={'verbose_name': 'Revenue plan management', 'verbose_name_plural': 'Revenue plan management'},
        ),
    ]
