# Generated by Django 4.2 on 2024-10-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_allexpense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allexpense',
            options={'verbose_name': 'Expense performed', 'verbose_name_plural': 'Expense performed'},
        ),
        migrations.AlterModelOptions(
            name='allpotablewaterservicemanagement',
            options={'verbose_name': 'Potable water service performed', 'verbose_name_plural': 'potable water service performed'},
        ),
        migrations.AlterModelOptions(
            name='allrevenue',
            options={'verbose_name': 'Revenue performed', 'verbose_name_plural': 'Revenue performed'},
        ),
        migrations.AlterModelOptions(
            name='detailcostmanagement',
            options={'verbose_name_plural': 'Detail cost'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'verbose_name': 'Expense plan', 'verbose_name_plural': 'Expense plan'},
        ),
        migrations.AlterModelOptions(
            name='generalleisure',
            options={'verbose_name': 'General leisure', 'verbose_name_plural': 'General leisure'},
        ),
        migrations.AlterModelOptions(
            name='potablewaterservicetype',
            options={'verbose_name': 'Potable water service plan', 'verbose_name_plural': 'Potable water service plan'},
        ),
        migrations.AlterModelOptions(
            name='revenuetype',
            options={'verbose_name': 'Revenue plan', 'verbose_name_plural': 'Revenue plan'},
        ),
    ]
