# Generated by Django 4.2 on 2024-10-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0019_auto_20240930_2156'),
        ('process', '0005_alter_allexpense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setups.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potablewaterservicetype',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setups.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenuetype',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setups.department'),
            preserve_default=False,
        ),
    ]
