# Generated by Django 4.2 on 2024-10-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_expensetype_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPerformanceRank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('total_plan', models.CharField(max_length=150)),
                ('total_performed', models.CharField(max_length=150)),
                ('performance_percentage', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'የስራ ሂደት የአፈጻጸም ደረጃ',
                'verbose_name_plural': 'የስራ ሂደት የአፈጻጸም ደረጃ',
                'db_table': 'DEPARTMENTPERFORMANCERANK',
                'managed': False,
            },
        ),
    ]
