# Generated by Django 5.1.7 on 2025-03-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_departmentperformancerank'),
        ('setups', '0046_task_content_type_task_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potablewaterservicetype',
            name='Service_title_amharic',
            field=models.ForeignKey(limit_choices_to={'task_type': 'Potable Water'}, on_delete=django.db.models.deletion.CASCADE, to='setups.task'),
        ),
    ]
