# Generated by Django 5.1.7 on 2025-03-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_alter_potablewaterservicetype_service_title_amharic'),
        ('setups', '0047_remove_task_content_type_remove_task_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potablewaterservicetype',
            name='Service_title_english',
        ),
        migrations.AlterField(
            model_name='potablewaterservicetype',
            name='Service_title_amharic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.task'),
        ),
    ]
