# Generated by Django 5.1.7 on 2025-03-23 10:46

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_remove_expensetype_expense_title_english_and_more'),
        ('setups', '0047_remove_task_content_type_remove_task_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuetype',
            name='Revenue_title_amharic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', on_delete=django.db.models.deletion.CASCADE, to='setups.task'),
        ),
    ]
