# Generated by Django 5.1.7 on 2025-03-23 10:55

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_alter_revenuetype_revenue_title_amharic'),
        ('setups', '0047_remove_task_content_type_remove_task_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='Expense_title_amharic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', on_delete=django.db.models.deletion.CASCADE, to='setups.task'),
        ),
        migrations.AlterField(
            model_name='potablewaterservicetype',
            name='Service_title_amharic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', on_delete=django.db.models.deletion.CASCADE, to='setups.task'),
        ),
    ]
