# Generated by Django 5.0.6 on 2024-06-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'update or register single bill', 'verbose_name_plural': 'update or register single bills'},
        ),
        migrations.AlterModelOptions(
            name='billcancellation',
            options={'managed': True, 'verbose_name': 'Cancel single bill', 'verbose_name_plural': 'Cancel single bills'},
        ),
        migrations.AlterModelOptions(
            name='bulkbillupload',
            options={'managed': True, 'verbose_name': 'Bulk bill registration', 'verbose_name_plural': 'Bulk bill registrations'},
        ),
        migrations.AlterModelTable(
            name='billcancellation',
            table='',
        ),
        migrations.AlterModelTable(
            name='bulkbillupload',
            table='',
        ),
    ]
