# Generated by Django 5.0.6 on 2024-06-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bill_options_alter_billcancellation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkbillupload',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='bulkbillupload',
            table=None,
        ),
    ]
