# Generated by Django 5.0.6 on 2024-06-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_bulkbillupload_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkbillupload',
            name='uploaded_file',
            field=models.FileField(upload_to=''),
        ),
    ]
