# Generated by Django 5.0.6 on 2024-06-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_alter_bulkbillupload_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkbillupload',
            name='uploaded_file',
            field=models.FileField(upload_to='bulk_bill_uploads/'),
        ),
    ]
