# Generated by Django 3.2.25 on 2024-08-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_alter_bill_status_alter_billcancellation_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Update or register single bill', 'verbose_name_plural': 'Update or register single bills'},
        ),
    ]
