# Generated by Django 3.2.25 on 2024-09-14 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0007_alter_bill_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField()),
                ('Deposite', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('Withdrawal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('Balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('Registered_at', models.DateTimeField(auto_now=True, verbose_name='Registered at')),
                ('Registered_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl_by44', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_by44', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
