# Generated by Django 5.1.7 on 2025-03-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0008_bankbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsync',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billsync',
            name='bank_transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billsync',
            name='bill_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='billsync',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
