# Generated by Django 5.1.7 on 2025-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_rename_upload_date_billsyncfile_download_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsyncfile',
            name='downloaded_file',
            field=models.FileField(upload_to='sync_files/'),
        ),
        migrations.AlterField(
            model_name='billsyncfile',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Not Success', 'Not Success')], default='Not Success', max_length=20),
        ),
    ]
