# Generated by Django 5.1.7 on 2025-03-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0011_alter_billsyncfile_downloaded_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsyncfile',
            name='downloaded_file',
            field=models.FileField(blank=True, null=True, upload_to='sync_files/'),
        ),
    ]
