# Generated by Django 5.1.7 on 2025-03-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0012_alter_billsyncfile_downloaded_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkBillUpdate',
        ),
    ]
