# Generated by Django 5.1.7 on 2025-03-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0013_delete_bulkbillupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsyncfile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
