# Generated by Django 5.1.7 on 2025-03-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0014_alter_billsyncfile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRegistartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index1', models.IntegerField()),
                ('bill_id', models.TextField()),
                ('bill_description', models.CharField(max_length=255)),
                ('bill_reason', models.CharField(max_length=255)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=25)),
                ('customer_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('prev_read', models.PositiveBigIntegerField()),
                ('curr_read', models.PositiveBigIntegerField()),
                ('consumption', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'bankregistartion',
                'managed': False,
            },
        ),
    ]
