# Generated by Django 5.1.7 on 2025-03-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0018_alter_bankupload_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankupload',
            options={'managed': False, 'ordering': ['-due_date'], 'verbose_name': 'Bank Upload', 'verbose_name_plural': 'Bank Uploads'},
        ),
    ]
