# Generated by Django 5.1.7 on 2025-03-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0019_alter_bankupload_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankupload',
            options={'managed': False, 'ordering': ['-due_date']},
        ),
    ]
