# Generated by Django 5.1.7 on 2025-03-31 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0020_alter_bankupload_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkbillupload',
            options={},
        ),
        migrations.AddField(
            model_name='bulkbillupload',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulkbillupload',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Not Success', 'Not Success'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkbillupload',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
