# Generated by Django 5.1.7 on 2025-04-04 14:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0021_alter_bulkbillupload_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Register single bill', 'verbose_name_plural': 'Register single bills'},
        ),
        migrations.AlterModelOptions(
            name='bulkbillupload',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Bulk Bill Upload', 'verbose_name_plural': 'Bulk Bill Uploads'},
        ),
        migrations.RenameField(
            model_name='bulkbillupload',
            old_name='cancel_date',
            new_name='processed_date',
        ),
        migrations.AddField(
            model_name='bulkbillupload',
            name='error_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bulkbillupload',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkbillupload',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkbillupload',
            name='uploaded_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bulkbillupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkbillupload',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bulkbillupload',
            name='uploaded_file',
            field=models.FileField(help_text='Upload CSV file with bill data', upload_to='bulk_bill_uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
