# Generated by Django 5.1.7 on 2025-04-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0023_bulkbilluploading'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkBillUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='bulk_bill_uploads/')),
                ('status', models.CharField(blank=True, default='Pending', max_length=20, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bulk bill registration',
                'verbose_name_plural': 'Bulk bill registrations',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Update single bill', 'verbose_name_plural': 'Update single bills'},
        ),
    ]
