# Generated by Django 5.1.7 on 2025-04-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0024_bulkbilluploaded_alter_bill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkbilluploaded',
            options={'managed': True, 'verbose_name': 'Bulk Registration', 'verbose_name_plural': 'Bulk Registrations'},
        ),
    ]
