# Generated by Django 5.1.7 on 2025-04-08 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0025_alter_bulkbilluploaded_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkBillsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bulk_bill_uploads/')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('api_key', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Bulk Bills Upload',
                'verbose_name_plural': 'Bulk Bills Uploads',
            },
        ),
    ]
