# Generated by Django 5.1.7 on 2025-04-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0026_bulkbillsupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkBillUpload',
        ),
    ]
