# Generated by Django 5.1.7 on 2025-04-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0027_delete_bulkbillupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkBillsUpload',
        ),
        migrations.DeleteModel(
            name='BulkBillUploaded',
        ),
        migrations.DeleteModel(
            name='BulkBillUploading',
        ),
    ]
