# Generated by Django 5.1.7 on 2025-04-08 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0029_bulkbillupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkbillupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bulk Bill Upload', 'verbose_name_plural': 'Bulk Bill Uploads'},
        ),
        migrations.AlterField(
            model_name='bulkbillupload',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload Time'),
        ),
        migrations.AlterField(
            model_name='bulkbillupload',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error Details'),
        ),
        migrations.AlterField(
            model_name='bulkbillupload',
            name='file',
            field=models.FileField(upload_to='bulk_bill_uploads/', verbose_name='Bill File'),
        ),
        migrations.AlterField(
            model_name='bulkbillupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
