# Generated by Django 5.2.1 on 2025-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0030_alter_bulkbillupload_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsync',
            name='max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
