# Generated by Django 3.2.25 on 2024-08-09 15:47

import bills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebele', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('month', models.CharField(default=bills.models.get_current_month, max_length=50)),
                ('year', models.CharField(default=bills.models.get_current_year, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('previous_read', models.PositiveBigIntegerField(help_text='ያለፈው ወር ንባብ')),
                ('current_read', models.PositiveBigIntegerField(help_text='የዚህ ወር ንባብ')),
                ('consumption', models.PositiveBigIntegerField(help_text='የዚህ ወር ፍጆታ')),
                ('block1', models.PositiveBigIntegerField()),
                ('block2', models.PositiveBigIntegerField()),
                ('block3', models.PositiveBigIntegerField()),
                ('block4', models.PositiveBigIntegerField()),
                ('block5', models.PositiveBigIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('status', models.CharField(choices=[('Sold', 'Sold'), ('Not Sold', 'Not Sold')], default='Not Sold', max_length=50)),
            ],
        ),
    ]
