# Generated by Django 3.2.25 on 2024-09-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0018_bankpaymenttype'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_bills', to='setups.banktype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterbill',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_bills', to='setups.paymenttype'),
            preserve_default=False,
        ),
    ]
