# Generated by Django 4.2 on 2024-10-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_unsold_bills'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsoldBills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=150)),
                ('months_not_sold', models.CharField(max_length=150, verbose_name='unsold months')),
                ('total_price', models.CharField(max_length=150, verbose_name='unsold price')),
                ('penalty', models.CharField(max_length=150)),
                ('total_unsold_price_with_penalty', models.CharField(max_length=150, verbose_name='total price')),
            ],
            options={
                'verbose_name': 'Unsold bill',
                'verbose_name_plural': 'Unsold bills',
                'db_table': 'V_UNSOLD_BILLS',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='unsold_bills',
        ),
    ]
