# Generated by Django 4.2 on 2024-10-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_unsoldbills_delete_unsold_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='payment_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='payment_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
