# Generated by Django 4.2 on 2024-10-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_waterbill_payment_end_waterbill_payment_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='bank',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='payment_type',
            field=models.CharField(max_length=100),
        ),
    ]
