# Generated by Django 4.2 on 2024-10-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_waterbill_bank_alter_waterbill_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
