# Generated by Django 5.1.3 on 2024-12-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_waterbill_created_at_waterbill_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputdata',
            options={'verbose_name': 'Calculate bill', 'verbose_name_plural': 'Calculate bills'},
        ),
    ]
