# Generated by Django 5.1.4 on 2025-01-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_handoverdetailreport_delete_materialsalereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverSummaryReport',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('SERVICE', models.CharField(max_length=100)),
                ('TOTAL_CONSUMPTION', models.CharField(max_length=100)),
                ('TOTAL_PRICE', models.CharField(max_length=100)),
                ('MONTH', models.CharField(max_length=100)),
                ('YEAR', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'የቢል መረካከቢያ አጠቃላይ ሪፖርት',
                'verbose_name_plural': 'የቢል መረካከቢያ አጠቃላይ ሪፖርት',
                'db_table': 'HANDOVER_SUMMARY_REPORT',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='handoverdetailreport',
            options={'managed': False, 'verbose_name': 'የቢል መረካከቢያ ዝርዝር ሪፖርት', 'verbose_name_plural': 'የቢል መረካከቢያ ዝርዝር ሪፖርት'},
        ),
    ]
