# Generated by Django 5.1.7 on 2025-03-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_handoversummaryreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbill',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='waterbill',
            name='payment_type',
        ),
    ]
