# Generated by Django 5.1.7 on 2025-03-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_remove_waterbill_bank_remove_waterbill_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='bill_id',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
