# Generated by Django 5.1.7 on 2025-03-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0014_waterbill_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='status',
            field=models.CharField(choices=[('For_sale_by_bank', 'For Sale by Bank'), ('For_sale_by_office', 'For Sale by Office'), ('Not Sold', 'Not Sold')], default='Not Sold', max_length=50),
        ),
    ]
