# Generated by Django 5.1.7 on 2025-03-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0015_alter_waterbill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_id', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('kebele', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=250)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('bank_transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'payment_method',
                'managed': False,
            },
        ),
    ]
