# Generated by Django 5.1.7 on 2025-03-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0016_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='status',
            field=models.CharField(choices=[('Sold_by_office', 'Sold by Office'), ('Not Sold', 'Not Sold')], default='Not Sold', max_length=50),
        ),
    ]
