# Generated by Django 5.1.7 on 2025-03-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0018_alter_waterbill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='status',
            field=models.CharField(choices=[('For_sale_by_bank', 'For Sale by Bank'), ('Sold_by_office', 'Sold by Office')], default='For Sale by Bank', max_length=50),
        ),
    ]
