# Generated by Django 5.1.7 on 2025-04-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0019_alter_waterbill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_count', models.IntegerField()),
            ],
            options={
                'db_table': 'bank_balance',
                'managed': False,
            },
        ),
    ]
