# Generated by Django 5.1.7 on 2025-04-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0020_bankbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='guage_rent',
            field=models.PositiveBigIntegerField(blank=True, help_text='የውኃ ቆጣሪ ኪራይ', null=True),
        ),
    ]
