# Generated by Django 5.1.7 on 2025-04-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0022_servicetransactionsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceTransactionSummary',
        ),
    ]
