# Generated by Django 5.1.7 on 2025-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0023_delete_servicetransactionsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSummaryPeriod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=250)),
                ('transaction_count', models.IntegerField()),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Service Transaction Summary',
                'verbose_name_plural': 'Service Transaction Summaries',
                'db_table': 'service_transaction_summary',
                'managed': False,
            },
        ),
    ]
