# Generated by Django 5.1.7 on 2025-04-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0024_paymentsummaryperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsummaryperiod',
            options={'managed': False, 'verbose_name': 'Service Types Transaction Summary', 'verbose_name_plural': 'Service Types Transaction Summaries'},
        ),
        migrations.AlterModelTable(
            name='paymentsummaryperiod',
            table='payment_summary_period',
        ),
    ]
