# Generated by Django 5.1.7 on 2025-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0025_alter_paymentsummaryperiod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
    ]
