# Generated by Django 5.1.7 on 2025-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0026_waterbill_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsoldPaymentSummaryPeriod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=250)),
                ('customer_count', models.IntegerField()),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'UnSold Bills by Service Types Summary',
                'verbose_name_plural': 'UnSold Bills by Service Types Summaries',
                'db_table': 'unsold_payment_summary_period',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='paymentsummaryperiod',
            options={'managed': False, 'verbose_name': 'Sold Bills by Service Types Summary', 'verbose_name_plural': 'Sold Bills by Service Types Summaries'},
        ),
    ]
