# Generated by Django 5.1.7 on 2025-05-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0027_unsoldpaymentsummaryperiod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedBalanceSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sold_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_unsold_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_transaction_count', models.IntegerField()),
                ('unsold_customer_count', models.IntegerField()),
            ],
            options={
                'db_table': 'combined_balance_summary',
                'managed': False,
            },
        ),
    ]
