# Generated by Django 5.1.7 on 2025-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0028_combinedbalancesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedBalanceSummaryByService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_sold_bill', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_unsold_bill', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sold_transaction_count', models.IntegerField()),
                ('unsold_customer_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Service Balance Summary',
                'verbose_name_plural': 'Service Balance Summaries',
                'db_table': 'combined_balance_summary_by_service',
                'ordering': ['-year', '-month', 'service_type'],
                'managed': False,
            },
        ),
    ]
