# Generated by Django 5.1.7 on 2025-05-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0029_combinedbalancesummarybyservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinedbalancesummary',
            options={'managed': False, 'ordering': ['-year', '-month'], 'verbose_name': 'Combined Balance Summary', 'verbose_name_plural': 'Combined Balance Summaries'},
        ),
    ]
