# Generated by Django 5.0.4 on 2024-04-13 08:29

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateTimeField(verbose_name='ቀን')),
                ('Turned_total', models.CharField(max_length=150, verbose_name='የዞረ')),
                ('Income', models.CharField(max_length=150, verbose_name='ገቢ')),
                ('Total_income', models.CharField(max_length=150, verbose_name='ጠ/ገቢ')),
                ('Cost', models.CharField(max_length=150, verbose_name='ወጪ')),
                ('Balance', models.CharField(max_length=150, verbose_name='ከወጪ ቀሪ')),
                ('Remark', models.CharField(blank=True, max_length=150, verbose_name='ምርመራ')),
                ('Registered_at', models.DateTimeField(auto_now=True, verbose_name='Registered at')),
                ('Registered_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rr1', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ur1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault Control',
                'verbose_name_plural': 'Vault Controls',
            },
        ),
    ]
