# Generated by Django 5.0.4 on 2024-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultcontrol',
            name='Date',
            field=models.DateField(verbose_name='ቀን'),
        ),
    ]
