# Generated by Django 3.2.25 on 2024-09-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_expenseannualperformance_expensemonthlyperformance_expenseperformancefromapriltojune_expenseperforma'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='potablewaterperformancefromjulytoseptember',
            table='POTABLE_WATER_FROM_JULY_TO_SEPTEMBER',
        ),
    ]
