# Generated by Django 3.2.25 on 2024-09-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_potablewaterperformancefromjulytoseptember_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='potablewaterperformancefromjulytoseptember',
            table='"Potable_water_from_July_to_September"',
        ),
    ]
