# Generated by Django 3.2.25 on 2024-09-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_potablewaterperformancefromjulytoseptember_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potablewaterannualperformance',
            options={'managed': False, 'verbose_name': 'የመጠጥ ውሃ አመታዊ ሪፖርት', 'verbose_name_plural': 'የመጠጥ ውሃ አመታዊ ሪፖርት'},
        ),
        migrations.AlterModelOptions(
            name='potablewatermonthlyperformance',
            options={'managed': False, 'verbose_name': 'የመጠጥ ውሃ ወራዊ ሪፖርት', 'verbose_name_plural': 'የመጠጥ ውሃ ወራዊ ሪፖርት'},
        ),
        migrations.AlterModelOptions(
            name='potablewaterperformancefromapriltojune',
            options={'managed': False, 'verbose_name': 'የመጠጥ ውሃ 4ኛ ሩብ አመት ሪፖርት', 'verbose_name_plural': 'የመጠጥ ውሃ 4ኛ ሩብ አመት ሪፖርት'},
        ),
        migrations.AlterModelOptions(
            name='potablewaterperformancefromjanuarytomarch',
            options={'managed': False, 'verbose_name': 'የመጠጥ ውሃ 3ኛ ሩብ አመት ሪፖርት', 'verbose_name_plural': 'የመጠጥ ውሃ 3ኛ ሩብ አመት ሪፖርት'},
        ),
        migrations.AlterModelOptions(
            name='potablewaterperformancefromjulytoseptember',
            options={'managed': False, 'verbose_name': 'የመጠጥ ውሃ 1ኛ ሩብ አመት ሪፖርት', 'verbose_name_plural': 'የመጠጥ ውሃ 1ኛ ሩብ አመት ሪፖርት'},
        ),
        migrations.AlterModelOptions(
            name='potablewaterperformancefromoctobertodecember',
            options={'managed': False, 'verbose_name': 'የመጠጥ ውሃ 2ኛ ሩብ አመት ሪፖርት', 'verbose_name_plural': 'የመጠጥ ውሃ 2ኛ ሩብ አመት ሪፖርት'},
        ),
        migrations.AlterModelTable(
            name='potablewaterannualperformance',
            table='"Potable_water_annual_performance"',
        ),
        migrations.AlterModelTable(
            name='potablewatermonthlyperformance',
            table='"Potable_water_monthly_performance"',
        ),
        migrations.AlterModelTable(
            name='potablewaterperformancefromapriltojune',
            table='"Potable_water_from_April_to_June"',
        ),
        migrations.AlterModelTable(
            name='potablewaterperformancefromjanuarytomarch',
            table='"Potable_water_from_January_to_March"',
        ),
        migrations.AlterModelTable(
            name='potablewaterperformancefromoctobertodecember',
            table='"Potable_water_from_October_to_December"',
        ),
    ]
