# Generated by Django 3.2.25 on 2024-09-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20240925_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseannualperformance',
            options={'managed': False, 'verbose_name': 'የወጪ አመታዊ ሪፖርት', 'verbose_name_plural': 'የወጪ አመታዊ ሪፖርት'},
        ),
        migrations.AlterModelOptions(
            name='expensemonthlyperformance',
            options={'managed': False, 'verbose_name': 'የወጪ ወራዊ ሪፖርት', 'verbose_name_plural': 'የወጪ ወራዊ ሪፖርት'},
        ),
        migrations.AlterModelOptions(
            name='expenseperformancefromapriltojune',
            options={'managed': False, 'verbose_name': 'የወጪ 4ኛ ሩብ አመት ሪፖርት', 'verbose_name_plural': 'የወጪ 4ኛ ሩብ አመት ሪፖርት'},
        ),
        migrations.AlterModelOptions(
            name='expenseperformancefromjanuarytomarch',
            options={'managed': False, 'verbose_name': 'የወጪ 3ኛ ሩብ አመት ሪፖርት', 'verbose_name_plural': 'የወጪ 3ኛ ሩብ አመት ሪፖርት'},
        ),
        migrations.AlterModelOptions(
            name='expenseperformancefromjulytoseptember',
            options={'managed': False, 'verbose_name': 'የወጪ 1ኛ ሩብ አመት ሪፖርት', 'verbose_name_plural': 'የወጪ 1ኛ ሩብ አመት ሪፖርት'},
        ),
        migrations.AlterModelOptions(
            name='expenseperformancefromoctobertodecember',
            options={'managed': False, 'verbose_name': 'የወጪ 2ኛ ሩብ አመት ሪፖርት', 'verbose_name_plural': 'የወጪ 2ኛ ሩብ አመት ሪፖርት'},
        ),
    ]
