# Generated by Django 3.2.25 on 2024-09-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20240925_1833'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expenseperformancefromoctobertodecember',
            table='"Expense_from_October_to_December"',
        ),
    ]
