# Generated by Django 4.2 on 2024-10-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_expenseperformancefromoctobertodecember_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='revenueperformancefromjulytoseptember',
            table='RENEW_CONTRACT_CUSTOMERS',
        ),
    ]
