# Generated by Django 4.2 on 2024-10-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_revenueperformancefromjulytoseptember_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='revenueperformancefromjulytoseptember',
            table='Revenue_from_July_to_September',
        ),
    ]
