# Generated by Django 5.1.4 on 2025-03-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_revenueperformancefromjulytoseptember_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expenseannualperformance',
            table='"Expense_annual_performance"',
        ),
        migrations.AlterModelTable(
            name='expensemonthlyperformance',
            table='"Expense_monthly_performance"',
        ),
    ]
