# Generated by Django 5.1.7 on 2025-03-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_expenseannualperformance_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
