# Generated by Django 5.1.7 on 2025-03-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
