# Generated by Django 5.1.7 on 2025-03-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_delete_bill'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='revenueperformancefromoctobertodecember',
            table='REVENUE_FROM_OCTOBER_TO_DECEMBER',
        ),
    ]
