# Generated by Django 5.1.7 on 2025-03-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_revenueperformancefromoctobertodecember_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expenseannualperformance',
            table='Expense_annual_performance',
        ),
        migrations.AlterModelTable(
            name='expensemonthlyperformance',
            table='Expense_monthly_performance',
        ),
        migrations.AlterModelTable(
            name='expenseperformancefromoctobertodecember',
            table='Expense_from_October_to_December',
        ),
        migrations.AlterModelTable(
            name='potablewaterannualperformance',
            table='Potable_water_annual_performance',
        ),
        migrations.AlterModelTable(
            name='potablewatermonthlyperformance',
            table='Potable_water_monthly_performance',
        ),
        migrations.AlterModelTable(
            name='potablewaterperformancefromapriltojune',
            table='Potable_water_from_April_to_June',
        ),
        migrations.AlterModelTable(
            name='potablewaterperformancefromjanuarytomarch',
            table='Potable_water_from_January_to_March',
        ),
        migrations.AlterModelTable(
            name='potablewaterperformancefromjulytoseptember',
            table='Potable_water_from_July_to_September',
        ),
        migrations.AlterModelTable(
            name='potablewaterperformancefromoctobertodecember',
            table='Potable_water_from_October_to_December',
        ),
    ]
