# Generated by Django 5.0.6 on 2024-06-09 19:45

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amharic_first_name', models.CharField(max_length=100)),
                ('amharic_father_name', models.CharField(max_length=100)),
                ('amharic_last_name', models.CharField(max_length=100)),
                ('english_first_name', models.CharField(max_length=100)),
                ('english_father_name', models.CharField(max_length=100)),
                ('english_last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married ', 'Married')], max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('destrict', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('counter_number', models.CharField(max_length=100)),
                ('initial_read', models.CharField(max_length=100)),
                ('read_date', models.CharField(max_length=100)),
                ('contract_number', models.CharField(max_length=100)),
                ('contract_file', models.FileField(upload_to='contracts/')),
                ('customer_image', models.ImageField(upload_to='customer_images/')),
                ('customer_status', models.BooleanField()),
                ('created_at', models.DateField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c1', to=settings.AUTH_USER_MODEL)),
                ('guage_width', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.gaugewidth')),
                ('kebele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.kebele')),
                ('modified_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m1', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.servicetype')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.zone')),
            ],
        ),
    ]
