# Generated by Django 3.2.25 on 2024-08-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0006_auto_20240727_1143'),
        ('customers', '0003_client_month_client_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='setups.reader'),
        ),
    ]
