# Generated by Django 3.2.25 on 2024-08-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_client_reader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reader',
        ),
    ]
