# Generated by Django 3.2.25 on 2024-09-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_client_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='customer_status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active'), ('Transferred', 'Transferred'), ('Changed', 'Changed'), ('Disconnected', 'Disconnected')], default='Active', max_length=50),
        ),
    ]
