# Generated by Django 4.2 on 2024-10-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_client_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deposit',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
