# Generated by Django 4.2 on 2024-10-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_client_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='amharic_father_name',
            field=models.CharField(max_length=100, verbose_name='የአባት ስም'),
        ),
        migrations.AlterField(
            model_name='client',
            name='amharic_first_name',
            field=models.CharField(max_length=100, verbose_name='ስም'),
        ),
        migrations.AlterField(
            model_name='client',
            name='amharic_last_name',
            field=models.CharField(max_length=100, verbose_name='የአያት ስም'),
        ),
    ]
