# Generated by Django 4.2 on 2024-10-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_renewcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsiderationFree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=25)),
                ('kebele', models.CharField(max_length=25)),
                ('place_name', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=30)),
                ('house_number', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=30)),
                ('guage_width', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('customer_status', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=50)),
                ('number_of_years', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ከጋራ ግምት ክፍያ ውጪ የሆኑ ደንበኞች',
                'verbose_name_plural': 'ከጋራ ግምት ክፍያ ውጪ የሆኑ ደንበኞች ዝርዝር',
                'db_table': 'CONSIDERATION_FREE_CUSTOMERS',
                'managed': False,
            },
        ),
    ]
