# Generated by Django 4.2 on 2024-10-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_considerationfree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=25)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('total_bill', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ከጋራ ግምት ክፍያ ውጪ የሆኑ ደንበኞች',
                'verbose_name_plural': 'ከጋራ ግምት ክፍያ ውጪ የሆኑ ደንበኞች ዝርዝር',
                'db_table': 'CONSIDERATION_FREE_CUSTOMERS',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='deposit',
        ),
    ]
