# Generated by Django 4.2 on 2024-10-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_clearance_remove_client_deposit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearance',
            options={'managed': False, 'verbose_name': 'Clearance', 'verbose_name_plural': 'Clearances'},
        ),
        migrations.AlterModelTable(
            name='clearance',
            table='CLEARANCE',
        ),
    ]
