# Generated by Django 4.2 on 2024-10-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_clearance_options_alter_clearance_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='english_father_name',
            field=models.CharField(max_length=100, verbose_name='Father name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='english_first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='english_last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
    ]
