# Generated by Django 5.1.7 on 2025-03-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_client_english_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(default='DRB/', max_length=100, unique=True),
        ),
    ]
