# Generated by Django 5.1.7 on 2025-03-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='initial_read',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
