# Generated by Django 5.1.7 on 2025-03-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_client_initial_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images/'),
        ),
    ]
