# Generated by Django 5.1.7 on 2025-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='counter_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='destrict',
            field=models.CharField(default='South Achefer', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='house_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='place_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='read_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
