# Generated by Django 5.1.7 on 2025-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_client_contract_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
