# Generated by Django 5.1.7 on 2025-03-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_alter_client_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renewcontract',
            options={'managed': False, 'verbose_name': 'በየሁለት አመቱ ውል የሚታደስላቸው ደንበኞች', 'verbose_name_plural': 'በየሁለት አመቱ ውል የሚታደስላቸው ደንበኞች ዝርዝር'},
        ),
    ]
