# Generated by Django 5.1.7 on 2025-03-29 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_alter_renewcontract_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('counter_number', models.CharField(max_length=50, unique=True)),
                ('date_changed', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='customers.client')),
            ],
        ),
    ]
