# Generated by Django 5.1.7 on 2025-03-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_counternumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='counter_number',
        ),
    ]
