# Generated by Django 5.1.7 on 2025-04-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_alter_counternumber_date_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='amharic_father_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='amharic_first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='amharic_last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='english_father_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='english_first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='english_last_name',
        ),
        migrations.AddField(
            model_name='client',
            name='amharic_full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='ሙሉ ስም'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='english_full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Full name'),
            preserve_default=False,
        ),
    ]
