# Generated by Django 5.1.7 on 2025-04-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_alter_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married ', 'Married')], max_length=100, null=True),
        ),
    ]
