# Generated by Django 5.1.7 on 2025-04-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0027_alter_client_contact_number_alter_client_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_read',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
