# Generated by Django 5.1.7 on 2025-04-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_client_first_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deposit',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='customer_status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active'), ('Transferred', 'Transferred'), ('Disconnected', 'Disconnected')], default='Active', max_length=50),
        ),
    ]
