# Generated by Django 5.0.4 on 2024-04-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan_loaninline_delete_bankbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninline',
            name='Loan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
            preserve_default=False,
        ),
    ]
