# Generated by Django 5.0.4 on 2024-04-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loaninline_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaninline',
            name='Registered_at',
        ),
        migrations.RemoveField(
            model_name='loaninline',
            name='Registered_by',
        ),
        migrations.RemoveField(
            model_name='loaninline',
            name='Updated_by',
        ),
    ]
