# Generated by Django 5.0.4 on 2024-04-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_remove_loaninline_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loaninline',
            name='Date',
            field=models.DateField(),
        ),
    ]
