# Generated by Django 5.0.4 on 2024-04-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loan_date_alter_loaninline_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaninline',
            name='Balance',
        ),
        migrations.AddField(
            model_name='loan',
            name='Balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
