# Generated by Django 5.0.4 on 2024-04-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_remove_loaninline_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='Loan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Loan/ብድር'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='loaninline',
            name='Deposite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
