# Generated by Django 5.0.4 on 2024-04-24 15:01

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_loan_loan_alter_loan_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninline',
            name='Registered_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Registered at'),
        ),
        migrations.AddField(
            model_name='loaninline',
            name='Registered_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loaninline',
            name='Updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upd_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
