# Generated by Django 3.1 on 2020-08-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potablewaterrequest',
            name='Service_type',
            field=models.CharField(choices=[('Residence', 'Residence'), ('Trade_organization', 'Trade organization'), ('Public_government', 'Public government')], max_length=150),
        ),
    ]
