# Generated by Django 3.1 on 2020-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0002_auto_20200828_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcostrequest',
            name='For_consultation',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailcostrequest',
            name='For_information',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
