# Generated by Django 3.1 on 2020-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0003_auto_20200828_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Cashier',
            field=models.TextField(blank=True, default='በገቢ ደረሰኝ ቁጥር       ብር ስለከፈለ ቀሪው ስራ ታይቶ የሰራለት፡፡'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Cashier',
            field=models.TextField(blank=True, default='በገቢ ደረሰኝ ቁጥር       ብር ስለከፈለ ቀሪው ስራ ታይቶ የሰራለት፡፡', max_length=250),
        ),
        migrations.AlterField(
            model_name='namechangerequest',
            name='Cashier',
            field=models.TextField(blank=True, default='በገቢ ደረሰኝ ቁጥር       ብር ስለከፈለ ቀሪው ስራ ታይቶ የሰራለት፡፡', max_length=250),
        ),
        migrations.AlterField(
            model_name='potablewaterrequest',
            name='Cashier',
            field=models.TextField(blank=True, default='በገቢ ደረሰኝ ቁጥር       ብር ስለከፈለ ቀሪው ስራ ታይቶ የሰራለት፡፡'),
        ),
    ]
