# Generated by Django 3.1 on 2020-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0004_auto_20200828_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Adapter_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Adapter_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Amount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Elbow_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Elbow_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='For_Digging',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='For_Forms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='For_consultation',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='For_information',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Foss_set_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Foss_set_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Get_valve_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Get_valve_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Grand_total',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='HDP_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='HDP_tube_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Naples_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Naples_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Pipe_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Pipe_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Reducer_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Reducer_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Socket_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Socket_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='T_HDP_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='T_HDP_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='T_metal_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='T_metal_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Tape_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Tape_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Total_55',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Total_Form',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Union_HDP_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Union_HDP_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Union_metal_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Union_metal_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Water_meter_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Water_meter_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Adapter_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Adapter_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Amount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Elbow_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Elbow_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='For_Digging',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='For_waste',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Foss_set_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Foss_set_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Get_valve_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Get_valve_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Get_valve_change',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Grand_total',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='HDP_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='HDP_tube_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Naples_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Naples_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Pipe_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Pipe_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Reducer_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Reducer_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Socket_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Socket_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='T_HDP_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='T_HDP_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='T_metal_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='T_metal_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Tape_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Tape_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Union_HDP_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Union_HDP_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Union_metal_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Union_metal_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Water_meter_Quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Water_meter_change',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
