# Generated by Django 3.1 on 2020-08-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0005_auto_20200828_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalleisure',
            name='Check_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generalleisure',
            name='Check_payable',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generalleisure',
            name='Deposit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generalleisure',
            name='General',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generalleisure',
            name='Withdraw',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
