# Generated by Django 3.1 on 2020-08-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0008_watersupplyperformed_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Balance_Date',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(verbose_name='Date')),
                ('Total_deposite', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_withdrawal', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_balance', models.DecimalField(decimal_places=2, max_digits=250)),
            ],
            options={
                'db_table': 'Report_Balance_Date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report_Total_Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Date')),
                ('Total_deposite', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_withdrawal', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_balance', models.DecimalField(decimal_places=2, max_digits=250)),
            ],
            options={
                'db_table': 'Report_Total_Balance',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='financecostperformed',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='financecostperformed',
            name='Quarter',
        ),
        migrations.RemoveField(
            model_name='financeincomeperformed',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='financeincomeperformed',
            name='Quarter',
        ),
        migrations.RemoveField(
            model_name='humanresourceperformed',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='humanresourceperformed',
            name='Quarter',
        ),
        migrations.RemoveField(
            model_name='planningandcustomerissueperformed',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='planningandcustomerissueperformed',
            name='Quarter',
        ),
        migrations.RemoveField(
            model_name='watersupplyperformed',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='watersupplyperformed',
            name='Quarter',
        ),
        migrations.AddField(
            model_name='financecostperformed',
            name='First_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financecostperformed',
            name='First_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financecostperformed',
            name='Forth_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financecostperformed',
            name='Forth_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financecostperformed',
            name='Second_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financecostperformed',
            name='Second_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financecostperformed',
            name='Third_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financecostperformed',
            name='Third_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financecostperformed',
            name='Total_year_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='financeincomeperformed',
            name='First_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financeincomeperformed',
            name='First_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financeincomeperformed',
            name='Forth_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financeincomeperformed',
            name='Forth_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financeincomeperformed',
            name='Second_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financeincomeperformed',
            name='Second_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financeincomeperformed',
            name='Third_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financeincomeperformed',
            name='Third_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='financeincomeperformed',
            name='Total_year_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='humanresourceperformed',
            name='First_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='humanresourceperformed',
            name='First_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='humanresourceperformed',
            name='Forth_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='humanresourceperformed',
            name='Forth_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='humanresourceperformed',
            name='Second_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='humanresourceperformed',
            name='Second_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='humanresourceperformed',
            name='Third_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='humanresourceperformed',
            name='Third_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='humanresourceperformed',
            name='Total_year_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='planningandcustomerissueperformed',
            name='First_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='planningandcustomerissueperformed',
            name='First_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='planningandcustomerissueperformed',
            name='Forth_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='planningandcustomerissueperformed',
            name='Forth_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='planningandcustomerissueperformed',
            name='Second_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='planningandcustomerissueperformed',
            name='Second_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='planningandcustomerissueperformed',
            name='Third_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='planningandcustomerissueperformed',
            name='Third_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='planningandcustomerissueperformed',
            name='Total_year_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='watersupplyperformed',
            name='First_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='watersupplyperformed',
            name='First_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='watersupplyperformed',
            name='Forth_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='watersupplyperformed',
            name='Forth_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='watersupplyperformed',
            name='Second_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='watersupplyperformed',
            name='Second_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='watersupplyperformed',
            name='Third_Quarter_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='watersupplyperformed',
            name='Third_Quarter_performed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='watersupplyperformed',
            name='Total_year_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
