# Generated by Django 3.1 on 2020-08-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0010_auto_20200828_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBalanceDate',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(verbose_name='Date')),
                ('Total_deposite', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_withdrawal', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_balance', models.DecimalField(decimal_places=2, max_digits=250)),
            ],
            options={
                'db_table': 'Report_Balance_Date',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Report_Balance_Date',
        ),
        migrations.AlterField(
            model_name='generalleisure',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=250),
        ),
        migrations.AlterField(
            model_name='generalleisure',
            name='Deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=250),
        ),
        migrations.AlterField(
            model_name='generalleisure',
            name='Withdraw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=250),
        ),
    ]
