# Generated by Django 3.1 on 2020-08-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0011_auto_20200828_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Balance_Date',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(verbose_name='Date')),
                ('Total_deposite', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_withdrawal', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_balance', models.DecimalField(decimal_places=2, max_digits=250)),
            ],
            options={
                'db_table': 'Report_Balance_Date',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ReportBalanceDate',
        ),
    ]
