# Generated by Django 3.1 on 2020-08-28 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processolutions', '0012_auto_20200828_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Dates', models.DateField(verbose_name='Date')),
                ('Code', models.CharField(max_length=150)),
                ('Revenue_title_amharic', models.CharField(max_length=150)),
                ('Revenue_title_english', models.CharField(max_length=150)),
                ('Amount', models.DecimalField(decimal_places=2, default=0, max_digits=250)),
                ('Registered_date', models.CharField(max_length=150, verbose_name='Registered at')),
                ('Registered_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl_by11111', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_by11111', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue management',
                'verbose_name_plural': 'Revenue management',
            },
        ),
    ]
