# Generated by Django 3.1 on 2020-08-28 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processolutions', '0013_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='Amount',
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Dates', models.DateField(verbose_name='Date')),
                ('Code', models.CharField(max_length=150)),
                ('Expense_title_amharic', models.CharField(max_length=150)),
                ('Expense_title_english', models.CharField(max_length=150)),
                ('Registered_date', models.CharField(max_length=150, verbose_name='Registered at')),
                ('Registered_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl_by111111', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_by111111', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense management',
                'verbose_name_plural': 'Expense management',
            },
        ),
    ]
