# Generated by Django 3.1 on 2020-08-28 20:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processolutions', '0014_auto_20200828_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='ExpenseType',
        ),
        migrations.RenameModel(
            old_name='Revenue',
            new_name='RevenueType',
        ),
    ]
