# Generated by Django 3.1 on 2020-08-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0017_auto_20200828_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalleisure',
            name='Receipt_no',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
