# Generated by Django 3.1 on 2020-08-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0018_auto_20200828_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalleisure',
            name='Dates',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
