# Generated by Django 3.1 on 2020-08-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0019_auto_20200828_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalleisure',
            name='Dates',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
