# Generated by Django 3.1 on 2020-08-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0020_auto_20200828_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
