# Generated by Django 3.1 on 2020-08-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0021_delete_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='Registered_by',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='Updated_by',
        ),
        migrations.RemoveField(
            model_name='revenuetype',
            name='Registered_by',
        ),
        migrations.RemoveField(
            model_name='revenuetype',
            name='Updated_by',
        ),
        migrations.DeleteModel(
            name='ExpenseType',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
        migrations.DeleteModel(
            name='RevenueType',
        ),
    ]
