# Generated by Django 3.1 on 2020-08-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0023_expense_expensetype_revenue_revenuetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='Registered_by',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='Updated_by',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
