# Generated by Django 3.1 on 2020-08-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0025_expense_revenue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
