# Generated by Django 3.1 on 2020-08-28 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processolutions', '0027_auto_20200828_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpensesManagement',
            new_name='AllExpenses',
        ),
        migrations.RenameModel(
            old_name='RevenuesManagement',
            new_name='AllRevenue',
        ),
        migrations.AlterModelOptions(
            name='allexpenses',
            options={'verbose_name': 'All Expense management', 'verbose_name_plural': 'All Expense management'},
        ),
        migrations.AlterModelOptions(
            name='allrevenue',
            options={'verbose_name': 'All Revenue management', 'verbose_name_plural': 'All Revenue management'},
        ),
    ]
