# Generated by Django 3.1 on 2020-08-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0028_auto_20200828_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allrevenue',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='allrevenue',
            name='Registered_by',
        ),
        migrations.RemoveField(
            model_name='allrevenue',
            name='Updated_by',
        ),
        migrations.DeleteModel(
            name='AllExpenses',
        ),
        migrations.DeleteModel(
            name='AllRevenue',
        ),
    ]
