# Generated by Django 3.1 on 2020-09-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0031_auto_20200828_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Dates', models.DateField(verbose_name='Date')),
                ('Amount', models.DecimalField(decimal_places=2, default=0, max_digits=250)),
                ('Code', models.CharField(max_length=150)),
                ('Balance', models.DecimalField(decimal_places=2, default=0, max_digits=250)),
            ],
            options={
                'db_table': 'ExpenseReport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Dates', models.DateField(verbose_name='Date')),
                ('Amount', models.DecimalField(decimal_places=2, default=0, max_digits=250)),
                ('Code', models.CharField(max_length=150)),
                ('Balance', models.DecimalField(decimal_places=2, default=0, max_digits=250)),
            ],
            options={
                'db_table': 'RevenueReport',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='allexpense',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allrevenue',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=250),
            preserve_default=False,
        ),
    ]
