# Generated by Django 3.1 on 2020-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0032_auto_20200831_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Water_meter_Single_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
