# Generated by Django 3.1 on 2020-09-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0034_maintenancerequest_total_55'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Cashier',
            field=models.TextField(blank=True, default='በገቢ ደረሰኝ ቁጥር       ብር ስለከፈለ ቀሪው ስራ ታይቶ የሰራለት፡፡'),
        ),
    ]
