# Generated by Django 3.1 on 2020-09-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0035_auto_20200901_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allexpense',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=250),
        ),
        migrations.AlterField(
            model_name='allrevenue',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=250),
        ),
    ]
