# Generated by Django 3.1 on 2020-09-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0036_auto_20200901_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReportDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Dates', models.DateField(verbose_name='Date')),
                ('Code_id', models.CharField(max_length=150)),
                ('Code', models.CharField(max_length=150)),
                ('Balances', models.DecimalField(decimal_places=2, default=0, max_digits=250)),
            ],
            options={
                'db_table': 'ExpenseReportDate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueReportDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Dates', models.DateField(verbose_name='Date')),
                ('Code_id', models.CharField(max_length=150)),
                ('Code', models.CharField(max_length=150)),
                ('Balances', models.DecimalField(decimal_places=2, default=0, max_digits=250)),
            ],
            options={
                'db_table': 'RevenueReportDate',
                'managed': False,
            },
        ),
    ]
