# Generated by Django 3.1 on 2020-09-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0037_expensereportdate_revenuereportdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralReportBalanceDate',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(verbose_name='Date')),
                ('Total_deposite', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_withdrawal', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_balance', models.DecimalField(decimal_places=2, max_digits=250)),
            ],
            options={
                'db_table': 'GeneralReportBalanceDate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralReportTotalBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Date')),
                ('Total_deposite', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_withdrawal', models.DecimalField(decimal_places=2, max_digits=250)),
                ('Total_balance', models.DecimalField(decimal_places=2, max_digits=250)),
            ],
            options={
                'db_table': 'GeneralReportTotalBalance',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Report_Balance_Date',
        ),
        migrations.DeleteModel(
            name='Report_Total_Balance',
        ),
    ]
