# Generated by Django 3.1 on 2021-06-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0038_auto_20200901_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcostrequest',
            name='Cashier',
            field=models.TextField(blank=True, default='በገቢ ደረሰኝ ቁጥር       ብር ስለከፈለ ቀሪው ስራ ታይቶ ይሰራለት፡፡'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Cashier',
            field=models.TextField(blank=True, default='በገቢ ደረሰኝ ቁጥር       ብር ስለከፈለ ቀሪው ስራ ታይቶ ይሰራለት፡፡'),
        ),
        migrations.AlterField(
            model_name='namechangerequest',
            name='Cashier',
            field=models.TextField(blank=True, default='በገቢ ደረሰኝ ቁጥር       ብር ስለከፈለ ቀሪው ስራ ታይቶ ይሰራለት፡፡', max_length=250),
        ),
        migrations.AlterField(
            model_name='potablewaterrequest',
            name='Cashier',
            field=models.TextField(blank=True, default='በገቢ ደረሰኝ ቁጥር       ብር ስለከፈለ ቀሪው ስራ ታይቶ ይሰራለት፡፡'),
        ),
    ]
