# Generated by Django 5.0.4 on 2024-04-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0039_auto_20210608_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailcostrequest',
            options={'verbose_name_plural': 'የ55% አገልግሎት ክፍያ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='detailcostrequestcashier',
            options={'verbose_name_plural': 'ለንብረትና ገንዘብ ያዥ የስራ ሂደት 55% አገልግሎት ክፍያ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='detailcostrequestincomeofficer',
            options={'verbose_name_plural': 'ለገቢ ግዥ ፋይናንስ የስራ ሂደት 55% አገልግሎት ክፍያ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='detailcostrequestpotablewater',
            options={'verbose_name_plural': 'ለመጠጥ ዉኃ የስራ ሂደት 55% አገልግሎት ክፍያ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'verbose_name_plural': 'የጥገና ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequestcashier',
            options={'verbose_name_plural': 'ለንብረትና ገንዘብ ያዥ የስራ ሂደት የጥገና ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequestincomeofficer',
            options={'verbose_name_plural': 'ለገቢ ግዥ ፋይናንስ የስራ ሂደት የጥገና ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequestpotablewater',
            options={'verbose_name_plural': 'ለመጠጥ ዉኃ የስራ ሂደት የጥገና ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='namechangerequest',
            options={'verbose_name_plural': 'የስም ለውጥ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='namechangerequestbillprocessor',
            options={'verbose_name_plural': 'ለቢልና ግምት ክፍል የስራ ሂደት የስም ለውጥ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='namechangerequestcashier',
            options={'verbose_name_plural': 'ለንብረትና ገንዘብ ያዥ የስራ ሂደት የስም ለውጥ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='namechangerequestincomeofficer',
            options={'verbose_name_plural': 'ለገቢ ግዥ ፋይናንስ የስራ ሂደት የስም ለውጥ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='potablewaterrequest',
            options={'verbose_name_plural': 'የአዲስ ደንበኛ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='potablewaterrequestcashier',
            options={'verbose_name_plural': 'ለንብረትና ገንዘብ ያዥ የስራ ሂደት የአዲስ ደንበኛ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='potablewaterrequestincomeofficer',
            options={'verbose_name_plural': 'ለገቢ ግዥ ፋይናንስ የስራ ሂደት  የአዲስ ደንበኛ ጥያቄ'},
        ),
        migrations.AlterModelOptions(
            name='potablewaterrequestpotablewater',
            options={'verbose_name_plural': 'ለመጠጥ ዉኃ የስራ ሂደት የአዲስ ደንበኛ ጥያቄ'},
        ),
    ]
