# Generated by Django 5.0.4 on 2024-04-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0040_alter_detailcostrequest_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockManagement',
        ),
    ]
