# Generated by Django 5.0.4 on 2024-04-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processolutions', '0041_delete_stockmanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
