# Generated by Django 3.2.25 on 2024-10-03 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title or subject of the challenge', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the challenge')),
                ('incident_type', models.CharField(choices=[('technical', 'Technical'), ('logistical', 'Logistical'), ('safety', 'Safety'), ('other', 'Other')], default='other', help_text='Type of challenge or incident', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Priority level of the challenge', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', help_text='Current status of the report', max_length=20)),
                ('reported_on', models.DateTimeField(default=django.utils.timezone.now, help_text='When the challenge was reported')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='When the challenge was last updated')),
                ('location', models.CharField(blank=True, help_text='Location of the challenge or incident', max_length=200, null=True)),
                ('supporting_documents', models.FileField(blank=True, help_text='Any supporting documents related to the challenge', null=True, upload_to='challenges/documents/')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes about the challenge', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to resolve the challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_challenges', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(help_text='User who reported the challenge', on_delete=django.db.models.deletion.CASCADE, related_name='reported_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
