# Generated by Django 3.2.25 on 2024-10-03 15:48

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='reported_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, help_text='User who reported the challenge', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
