# Generated by Django 5.0.6 on 2024-06-16 14:36

import reads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputDataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default=reads.models.InputDataSheet.get_current_month, max_length=50)),
                ('year', models.CharField(default=reads.models.InputDataSheet.get_current_year, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterRead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('month', models.CharField(default=reads.models.WaterRead.get_current_month, max_length=50)),
                ('year', models.CharField(default=reads.models.WaterRead.get_current_year, max_length=50)),
                ('previous_read', models.BigIntegerField(help_text='ያለፈው ወር ንባብ')),
                ('current_read', models.BigIntegerField(help_text='የዚህ ወር ንባብ')),
                ('consumption', models.BigIntegerField(help_text='የዚህ ወር ፍጆታ')),
                ('next_my', models.PositiveIntegerField(default=0, verbose_name='Season flag')),
            ],
        ),
    ]
