# Generated by Django 3.2.25 on 2024-08-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0002_waterread_reader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterread',
            name='reader',
        ),
    ]
