# Generated by Django 3.2.25 on 2024-08-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0003_remove_waterread_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterread',
            name='current_read',
            field=models.BigIntegerField(blank=True, help_text='የዚህ ወር ንባብ', null=True),
        ),
    ]
