# Generated by Django 3.2.25 on 2024-08-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0007_zone_reader'),
        ('reads', '0004_alter_waterread_current_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterread',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_reads', to='setups.zone'),
            preserve_default=False,
        ),
    ]
