# Generated by Django 3.2.25 on 2024-09-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0005_waterread_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=3)),
            ],
        ),
    ]
