# Generated by Django 3.2.25 on 2024-09-10 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0006_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterread',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reads.schedule'),
            preserve_default=False,
        ),
    ]
