# Generated by Django 3.2.25 on 2024-09-18 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0008_remove_waterread_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterread',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reads.schedule'),
        ),
    ]
