# Generated by Django 3.2.25 on 2024-09-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0012_servicecharge'),
        ('reads', '0011_alter_waterread_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterread',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setups.zone'),
        ),
    ]
