# Generated by Django 3.2.25 on 2024-09-27 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0012_servicecharge'),
        ('reads', '0013_remove_waterread_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterread',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_reads', to='setups.zone'),
            preserve_default=False,
        ),
    ]
