# Generated by Django 3.2.25 on 2024-09-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0016_waterread_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterread',
            name='zone',
        ),
    ]
