# Generated by Django 3.2.25 on 2024-09-27 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0013_alter_zone_id'),
        ('reads', '0020_remove_waterread_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterread',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='setups.zone'),
        ),
    ]
