# Generated by Django 3.2.25 on 2024-09-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0014_alter_zone_id'),
        ('reads', '0021_waterread_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterread',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='setups.zone'),
            preserve_default=False,
        ),
    ]
