# Generated by Django 4.2 on 2024-10-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0022_alter_waterread_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionZeroCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('consecutive_zero_count', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Consumptions zero count',
                'verbose_name_plural': 'Consumptions zero counts',
                'db_table': 'v_consumptions_zero_count',
                'managed': False,
            },
        ),
    ]
