# Generated by Django 5.1.3 on 2024-12-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0023_consumptionzerocount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('READER_ID', models.IntegerField()),
                ('NAME', models.CharField(max_length=100)),
                ('STATUS', models.CharField(max_length=100)),
                ('ZONE_NAME', models.CharField(max_length=100)),
                ('READINGS_COUNT', models.CharField(max_length=100)),
                ('TOTAL_CONSUMPTION', models.CharField(max_length=100)),
                ('DISCREPANCIES', models.CharField(max_length=100)),
                ('RANK_BY_READINGS', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Reader comparison',
                'verbose_name_plural': 'Reader comparisons',
                'db_table': 'reader_comparison',
                'managed': False,
            },
        ),
    ]
