# Generated by Django 5.1.3 on 2024-12-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0025_alter_inputdatasheet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterread',
            name='consumption',
            field=models.BigIntegerField(blank=True, help_text='የዚህ ወር ፍጆታ', null=True),
        ),
    ]
