# Generated by Django 5.1.4 on 2025-02-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0026_alter_waterread_consumption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterread',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='waterread',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
