# Generated by Django 5.1.4 on 2025-02-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0027_alter_waterread_options_alter_waterread_schedule'),
        ('setups', '0036_alter_nutrition_grade_alter_tuitionformula_grade'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='waterread',
            constraint=models.UniqueConstraint(fields=('code', 'zone', 'month', 'year', 'previous_read', 'current_read', 'consumption', 'next_my', 'schedule'), name='unique_water_read'),
        ),
    ]
