# Generated by Django 5.1.4 on 2025-02-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0028_waterread_unique_water_read'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='waterread',
            name='unique_water_read',
        ),
    ]
