# Generated by Django 3.2.25 on 2024-09-14 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setups', '0009_itemlists_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Quantity', models.PositiveIntegerField()),
                ('Individual_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Material_status', models.BooleanField(default=True)),
                ('Registered_at', models.DateTimeField(auto_now=True, verbose_name='Registered at')),
                ('Measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.measurement')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.itemlists')),
                ('Registered_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl_by5', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_by5', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
