# Generated by Django 5.1.4 on 2025-01-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSaleReport',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('NAME', models.CharField(max_length=100)),
                ('QUANTITY', models.CharField(max_length=100)),
                ('SINGLE_PRICE', models.CharField(max_length=100)),
                ('TOTAL_PRICE', models.CharField(max_length=100)),
                ('MONTH_AMHARIC', models.CharField(max_length=100)),
                ('MONTH_ENGLISH', models.CharField(max_length=100)),
                ('YEAR', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ከዕቃ ሽያጭ ገቢ ዕለታዊ ሪፖርት',
                'db_table': 'MATERIALSALEREVENUEREPORT',
                'managed': False,
            },
        ),
    ]
