# Generated by Django 5.1.4 on 2025-01-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_materialsalereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialsalereport',
            options={'managed': False, 'verbose_name': 'ከዕቃ ሽያጭ ገቢ ዕለታዊ ሪፖርት', 'verbose_name_plural': 'ከዕቃ ሽያጭ ገቢ ዕለታዊ ሪፖርት'},
        ),
    ]
