# Generated by Django 3.2.25 on 2024-09-14 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Category', models.CharField(choices=[('1', 'First type'), ('2', 'Second type'), ('3', 'Third type'), ('4', 'Forth type')], max_length=150)),
                ('Sub_category', models.CharField(choices=[('1', 'First type'), ('2', 'Second type'), ('3', 'Third type'), ('4', 'Forth type')], max_length=150)),
                ('Complain_type', models.CharField(choices=[('1', 'First type'), ('2', 'Second type'), ('3', 'Third type'), ('4', 'Forth type')], max_length=150)),
                ('Nature_of_complaint', models.CharField(max_length=150)),
                ('Complain_details', models.TextField(max_length=250)),
                ('Complain_related', models.FileField(max_length=254, upload_to='documents/%Y/%m/%d')),
                ('Complained_at', models.DateTimeField(auto_now=True, verbose_name='Registered at')),
                ('Registered_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='z2', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='z1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complain management system',
                'verbose_name_plural': 'Complain management systems',
            },
        ),
    ]
